services:
    postgres:
        image: postgres:latest
        container_name: postgress_container
        restart: always
        environment:
            POSTGRES_USER: yuri
            POSTGRES_PASSWORD: 12345678
            POSTGRES_DB: yuri
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - network-db-net

    server:
        build: .
        container_name: "api"
        ports:
            - "3030:3030"
        env_file:
            - .env-docker
        volumes:
            - ./:/app
        networks:
            - network-db-net
        depends_on:
            - postgres

volumes:
    postgres_data:
        driver: local
networks:
    network-db-net:
